# Use postgres/example user/password credentials
version: '3.1'

services:
  lucky_db:
    container_name: lucky_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: lucky_challenge
    ports:
      - 5432:5432
  lucky_api:
    container_name: lucky_api
    build: .
    restart: always
    ports:
      - 3000:3000
  lucky_redis:
    image: redis:7.0.8-alpine
    restart: always
    ports:
      - 6379:6379
